version: '3.8'

services:
  database:
    container_name: database
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - my-network

  backend:
    container_name: back
    build:
      context: .
      dockerfile: src/Backend/src/FundacionAMA.API/Dockerfile
    environment:  
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - '7130:7130'
    depends_on:
      - database
    networks:
      - my-network
    platform: linux/amd64
 
  frontend:
    container_name: front
    build:
      context: .
      dockerfile: src/Frontend/Dockerfile.frontend
    ports:
      - '4200:80'
    networks:
      - my-network 
    platform: linux/amd64

networks:
  my-network: