name: AMA Docker Images

on:
  push:
    branches:
      - main 

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u fundama --password-stdin

    - name: Build and Push Backend Image
      run: |
        IMAGE_TAG=$(date '+%Y%m%d%H%M%S')
        docker build -t fundama/full-platform:backend-latest -t fundama/full-platform:backend-$IMAGE_TAG -f src/Backend/src/FundacionAMA.API/Dockerfile . --platform linux/amd64
        docker push fundama/full-platform:backend-latest
        docker push fundama/full-platform:backend-$IMAGE_TAG
        

    - name: Build and Push Frontend Image
      run: |
        IMAGE_TAG=$(date '+%Y%m%d%H%M%S')
        docker build -t fundama/full-platform:frontend-latest -t fundama/full-platform:frontend-$IMAGE_TAG -f src/Frontend/Dockerfile.frontend . --platform linux/amd64
        docker push fundama/full-platform:frontend-latest
        docker push fundama/full-platform:frontend-$IMAGE_TAG
